Repository FRONTENDBOOTCAMP-13th/9RoDigital, pull requests merged in 2025-03, with the labels that each got.

#2 Add custom labels config
  labels.json
Labels: ⚙️ Setting

#5 배포 테스트
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.cjs
  .vscode/settings.json
  index.html
  labels.json
Labels: ✅ Test

#26 Feature/button/hyunsoo
  index.html
  src/components/button/accentButtonHandler.js
  src/components/button/button.html
  src/main.js
  src/style.css
  vite.config.js
Labels: ✨ Feature

#37 Hotfix/setting
  .prettierrc.cjs
  labels.json
  package-lock.json
  package.json
  src/components/button/button.html
  src/components/footer/footer.html
  src/components/header/header.html
  src/components/landing/landing.html
  src/components/login/back-button.html
  src/components/login/background-image.html
  src/components/login/input.html
  src/components/login/login-button.html
  src/components/login/login.html
  src/components/login/sns-button.html
  src/components/login/text-list.html
  src/components/member/member.html
  src/components/member/profile.html
  src/components/mypage/Profile.html
  src/components/mypage/Subheader.html
  src/components/mypage/activity.html
  src/components/mypage/advertisement.html
  src/components/mypage/bookcase.html
  src/components/mypage/calendar.html
  src/components/mypage/highlights.html
  src/components/mypage/mypage.html
  src/components/mypage/riport.html
  src/components/mypage/suggestion.html
  src/components/mypage/write.html
  src/components/seaction5/original.html
  src/main.js
  vite.config.js
Labels: 🐞 BugFix

#43 이미지 주소 수정
  src/components/mypage/activity.html
  src/components/mypage/advertisement.html
  src/components/mypage/bookcase.html
  src/components/mypage/calendar.html
  src/components/mypage/mypage.html
  src/components/mypage/profile.html
  src/components/mypage/subheader.html
  src/components/mypage/suggestion.html
Labels: 🐞 BugFix

#51 Component/title/hyunsoo
  index.html
  src/components/section5/original.html
  src/components/section8/section8.html
  src/components/title/title.html
  vite.config.js
Labels: 🎨 Html&css, 📃 Docs

#53 🎁Modify : section5 밀리 오리지널 index.html 연결 링크 추가 및 vite.config.js에 추가
  index.html
  vite.config.js
Labels: 🐞 BugFix

#57 feature/section02/hyunsoo
  index.html
  src/components/section2/section2.html
  vite.config.js
Labels: ✨ Feature

#68 피드페이지 구현
  index.html
  src/assets/icon/profile2.png
  src/assets/icon/profile3.png
  src/assets/icon/write.png
  src/assets/images/feed/feed1.jpg
  src/assets/images/feed/feed1back.jpg
  src/assets/images/feed/feed2.jpg
  src/assets/images/feed/feed2back.jpg
  src/assets/images/feed/feed3.jpeg
  src/assets/images/feed/feed3back.jpeg
  src/assets/images/feed/feed4.jpeg
  src/assets/images/feed/feed4back.jpeg
  src/assets/images/feed/hiright1.jpg
  src/assets/images/feed/review3.png
  src/assets/images/feed/review6.jpeg
  src/assets/images/feed/review7.png
  src/assets/images/feed/review8.png
  src/assets/images/feed/review9.jpeg
  src/assets/images/feed/riview.jpeg
  src/assets/images/feed/riview2.jpeg
  src/assets/images/feed/riview4.jpeg
  src/assets/images/feed/riview5.jpeg
  src/components/feed/bookoflife.html
  src/components/feed/feed.html
  src/components/feed/feedmain.html
  src/components/feed/highlights.html
  src/components/feed/post.html
  src/components/feed/review.html
  src/components/feed/select.html
  src/components/feed/subheader.html
  vite.config.js
Labels: ✨ Feature

#71 🐳Chore : 빌드 파일 수정
  home.html
  index.html
  vite.config.js
Labels: 🌏 Deploy

#77 Feature/index/hyunsoo
  README.md
  home.html
  index.html
  public/favicon.svg
  public/font/pretendardvariable.css
  public/font/woff2/PretendardVariable.woff2
  src/assets/icon/arrow_right.svg
  src/assets/icon/github.svg
  src/assets/icon/link_45deg.svg
  src/assets/icon/millie.svg
  src/assets/images/dongsu_profile.webp
  src/assets/images/hyunsoo_profile.webp
  src/assets/images/rogie_profile.webp
  src/assets/images/yujin_profile.webp
  src/assets/logo/willie-english.svg
  src/assets/logo/willie-logo.svg
  src/assets/logo/willie_korean.svg
  src/assets/logo/willie_korean_w.svg
  src/assets/logo/willie_purple_korean_logo.svg
  src/assets/logo/willie_symbol_w.svg
  src/assets/logo/willie_text.svg
  src/assets/logo/willie_text_w.svg
  src/components/button/accentButtonHandler.js
  src/main.js
  src/scripts/accordionHandler.js
  src/scripts/smoothScroll.js
  src/style.css
  vite.config.js
Labels: 🎨 Html&css, ✨ Feature

#84 배포 테스트(버그해결위해)
  src/assets/icon/arrow_top.svg
  src/components/button/accentButtonHandler.js
  src/components/button/button.html
  src/components/feed/feed.html
  src/components/login/login.html
  src/components/mypage/mypage.html
  src/components/section3/today.js
  src/components/section5/original.html
  src/main.js
  src/pages/home/home.html
  src/pages/popup/popup.js
  src/style.css
Labels: 🌏 Deploy, 🐞 BugFix

#93 Bugfix/main/rogie
  src/components/feed/feed.html
  src/components/footer/footer.js
  src/components/login/login.html
  src/components/member/member.html
  src/components/mypage/mypage.html
  src/components/quote-frames/quote-frames.html
  src/pages/home/home.html
Labels: 🐞 BugFix

#94 📝Docs : README.md 초안 작성
  README.md
Labels: 📃 Docs

#97 📝Docs: 디자인 및 서치 페이지 제대로 연결 안되는거 수정함
  src/components/feed/feed.html
  src/components/member/member.html
  src/components/mypage/mypage.html
  src/components/search/search.html
  src/pages/home/home.html
Labels: 🐞 BugFix

#99 Refactor/search/yujin
  src/assets/images/audio-01.webp
  src/assets/images/audio-02.webp
  src/assets/images/audio-03.webp
  src/assets/images/audio-04.webp
  src/assets/images/category-01.webp
  src/assets/images/category-02.webp
  src/assets/images/category-03.webp
  src/assets/images/category-04.webp
  src/assets/images/category-05.webp
  src/assets/images/category-06.webp
  src/assets/images/category-07.webp
  src/assets/images/category-08.webp
  src/assets/images/category-09.webp
  src/assets/images/category-10.webp
  src/assets/images/category-11.webp
  src/assets/images/category-12.webp
  src/assets/images/category-13.webp
  src/assets/images/category-14.webp
  src/assets/images/category-15.webp
  src/assets/images/category-16.webp
  src/assets/images/category-17.webp
  src/assets/images/category-18.webp
  src/assets/images/category-19.webp
  src/assets/images/category-20.webp
  src/assets/images/category-21.webp
  src/assets/images/category-22.webp
  src/assets/images/category-23.webp
  src/assets/images/category-24.webp
  src/assets/images/category-25.webp
  src/assets/images/category-26.webp
  src/assets/images/category-27.webp
  src/assets/images/category-28.webp
  src/assets/images/category-29.webp
  src/assets/images/category-30.webp
  src/components/member/member.html
  src/components/search/search.html
  src/components/search/search.js
  src/style.css
Labels: 🔨 Refactor

#101 🎁Modify : landing 컴포넌트 수정
  src/components/landing/landing.html
Labels: 🔨 Refactor

#102 피드,마이 페이지 오류 수정
  src/components/feed/feed.html
  src/components/mypage/mypage.html
Labels: 🔨 Refactor

#103 Bugfix/main/rogie
  index.html
  src/assets/images/section-04-08-sm.webp
  src/assets/images/section-04-08-xl.webp
  src/components/feed/feed.html
  src/components/footer/footer.html
  src/components/footer/footer.js
  src/components/header/header.html
  src/components/landing/landing.html
  src/components/member/member.html
  src/components/mypage/mypage.html
  src/components/search/search.html
  src/components/section3/section3.html
  src/components/section4/section4.html
  src/components/section5/original.html
  src/components/section7/thisbook.html
  src/pages/home/home.html
  src/pages/popup/popup.js
Labels: 🐞 BugFix

#106 Docs/readme/hyunsoo
  README.md
  src/components/footer/footer.js
  src/pages/home/home.html
Labels: 📃 Docs, 🐞 BugFix

#109 Docs/readme/hyunsoo
  README.md
Labels: 📃 Docs

#110 README.md 수정된 버전 main에 Merge
  README.md
Labels: 🌏 Deploy, 📃 Docs

#111 📝 Docs : 제목 ### -> ##으로 수정
  README.md
Labels: 📃 Docs

#112 📝 Docs : 역할 분배 추가
  README.md
Labels: 📃 Docs

#118 Fix/home qa/rogie
  src/components/footer/footer.js
  src/main.js
  src/pages/home/home.html
  src/scripts/hrefnotclick.js
Labels: 🥰 Accessibility

#117 Fix/qa comp/yujin
  src/components/member/member.html
  src/components/search/search.html
Labels: 🥰 Accessibility

#119 Fix/index qa/hyunsoo
  index.html
  public/apple-touch-icon-120x120.png
  public/apple-touch-icon-152x152.png
  public/apple-touch-icon-167x167.png
  public/apple-touch-icon-180x180.png
  public/robots.txt
  public/sitemap.xml
  public/willie_og_large_image.png
  public/willie_og_twitter_large_image.png
  src/components/book-badge/book-badge.html
  src/components/footer/footer.html
  src/components/header/header.html
  src/components/landing/landing.html
  src/components/section1/section1.html
  src/components/section2/section2.html
  src/components/section3/section3.html
  src/components/section5/original.html
  src/components/section6/thisbook.html
  src/components/section7/section7.html
  src/style.css
Labels: 💻 CrossBrowsing, 🔨 Refactor, 🥰 Accessibility

#120 웹 접근성, 웹 표준, SEO 최적화를 개선한 버전을 배포합니다.
  index.html
  public/apple-touch-icon-120x120.png
  public/apple-touch-icon-152x152.png
  public/apple-touch-icon-167x167.png
  public/apple-touch-icon-180x180.png
  public/robots.txt
  public/sitemap.xml
  public/willie_og_large_image.png
  public/willie_og_twitter_large_image.png
  src/components/book-badge/book-badge.html
  src/components/footer/footer.html
  src/components/footer/footer.js
  src/components/header/header.html
  src/components/landing/landing.html
  src/components/member/member.html
  src/components/search/search.html
  src/components/section1/section1.html
  src/components/section2/section2.html
  src/components/section3/section3.html
  src/components/section5/original.html
  src/components/section6/thisbook.html
  src/components/section7/section7.html
  src/main.js
  src/pages/home/home.html
  src/scripts/hrefnotclick.js
  src/style.css
Labels: 🌏 Deploy

#122 Hotfix/search console/hyunsoo
  public/apple-touch-icon-120x120.png
  public/apple-touch-icon-152x152.png
  public/apple-touch-icon-167x167.png
  public/apple-touch-icon-180x180.png
  public/google9a2bc52a17bfbbc6.html
Labels: 🌏 Deploy

#123 Google Search Console 등록을 위해 파일을 추가한 버전을 새로 배포합니다.
  public/apple-touch-icon-120x120.png
  public/apple-touch-icon-152x152.png
  public/apple-touch-icon-167x167.png
  public/apple-touch-icon-180x180.png
  public/google9a2bc52a17bfbbc6.html
Labels: 🌏 Deploy

#124 🎁Modify : Open Graph 태그, 트위터 카드 태그 썸네일 이미지 경로 변경
  index.html
Labels: 🌏 Deploy
